/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pgpainless.wot.kotlin-library-conventions")
    id("java-test-fixtures")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    // testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"

    // Logging
    api("org.slf4j:slf4j-api")
    testImplementation("ch.qos.logback:logback-classic")
}