/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pgpainless.wot.kotlin-library-conventions")
    id("java-test-fixtures")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    testImplementation(project(":pgpainless-wot-cli"))
    testImplementation(testFixtures(project(":wot-dijkstra")))

    //testFixturesImplementation("org.junit.jupiter:junit-jupiter-api")
    //testFixturesImplementation("org.junit.jupiter:junit-jupiter-params")
//    testFixturesRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    testFixturesApi(project(":pgpainless-wot"))

    // Logging
    testImplementation("ch.qos.logback:logback-classic")

    api(project(":pgpainless-wot"))
}