/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pgpainless.wot.kotlin-library-conventions")
    id("java-test-fixtures")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    testFixturesImplementation("org.junit.jupiter:junit-jupiter-api")

    testImplementation("ch.qos.logback:logback-classic")

    api(project(":wot-dijkstra"))
    api("org.pgpainless:pgpainless-core")
    // api("org.pgpainless:pgp-certificate-store:0.2.2")
    api("org.pgpainless:pgpainless-cert-d:0.2.2") {
        exclude("org.pgpainless:pgpainless-core")
    }

}