/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pgpainless.wot.kotlin-application-conventions")
}

dependencies {
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("ch.qos.logback:logback-classic")

    implementation(project(":pgpainless-wot"))
    implementation("ch.qos.logback:logback-classic")

    implementation("info.picocli:picocli")
    annotationProcessor("info.picocli:picocli-codegen")
}

application {
    // Define the main class for the application.
    mainClass.set("org.pgpainless.wot.cli.WotCLI")
}
