
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("pgpainless.wot.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("java-test-fixtures")
}

dependencies {
    constraints {
        testFixturesImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
        testFixturesImplementation("org.junit.jupiter:junit-jupiter-params:5.8.2")
    }
}