steps:
  - name: build
    image: gradle:8.8-jdk11
    commands:
      # Checkout code
      - git checkout $CI_COMMIT_BRANCH
      # Code works
      - gradle test
      # Code is clean
      - gradle check javadocAll
      # Code has coverage
      - gradle jacocoRootReport coverallsJacoco
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
